version: '3'

services:
  mysql:
    image: mysql:5.7
    hostname: webapp_mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_dev

  webapp:
    image: java:8
    links:
      - mysql:webapp_mysql
    volumes:
      - /root/temp/jar/spring-boot-docker-0.1.0.jar:/app/app.jar
    ports:
      - "80:80"
    command: "java -jar /app/app.jar --spring.profiles.active=dev"
